mode: testApi
api:
  name: Maestro
  namespace: maestro
  port: 8080
  concurrentJobs: 5

jira:
  name: JiraIntegration
  token: ""
  username: ""
  tenant_name: ""
  webhook_secret: ""

  status_allowed:
    initial_status: "Work in progress"
    final_status: "Concluído"

database:
  name: database
  user: ""
  password: ""
  db: ""
  url: ""
