services:
  maestro-core:
    build:
      context: .
      target: ${DOCKER_TARGET:-dev}
    env_file:
      - path: ./envs/.env.${DOCKER_TARGET:-dev}
        required: false
      - path: ./envs/.env.${DOCKER_TARGET:-dev}.secret
        required: false
    volumes:
      - ./:/app
    
    ports:
      - "8080:${PORT:-8080}"
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512m
