services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${MAESTRO_DATABASE_USER}
      POSTGRES_PASSWORD: ${MAESTRO_DATABASE_PASSWORD}
      POSTGRES_DB: ${MAESTRO_DATABASE_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maestro-core:
    build:
      context: .
      target: ${DOCKER_TARGET:-dev}
    env_file:
      - path: ./envs/.env.${DOCKER_TARGET:-dev}
        required: false
      - path: ./envs/.env.%{DOCKER_TARGET:-dev}.secret
        required: false
    volumes:
      - ./:/app
    ports:
      - "8080:${PORT:-8080}"

volumes:
  postgres_data: