job: football
jiraFields:
  need: Pesquisa
  system: Transfermarket
  attachmentFilename: "Input.csv"
  answerCommentTemplate: "Modelo de resposta"

container:
    image: imageName
    containerDir: scripts/football
indicators:
  timePerOp: 60
  timeSaved: 60
